"""P6 integration test — approval evidence from QA and judge artifacts.

Runs a full dev_cycle, waits for the QA and judge artifacts, then records an
approval using those artifact IDs as evidence.
"""
from __future__ import annotations

import time
from uuid import uuid4

import pytest


POLL_INTERVAL = 3.0
POLL_TIMEOUT = 1200.0


def _make_run_payload(project_id: str) -> dict:
    return {
        "project_id": project_id,
        "workflow_type": "dev_cycle",
        "idempotency_key": f"p6-approval-evidence-{uuid4().hex}",
    }


@pytest.fixture
def p6_approval_project(client, project_payload):
    payload = {
        **project_payload,
        "name": "Task Board Validator",
        "description": (
            "Build a minimal Python task board manager. "
            "Users can add tasks, move tasks between columns, and list tasks by column. "
            "Store state in memory only. "
            "Expose functions and a simple CLI wrapper. "
            "Include at least two pytest tests covering task creation and column movement."
        ),
    }
    resp = client.post("/projects", json=payload)
    assert resp.status_code == 201, resp.text
    return resp.json()


def _wait_for_terminal(client, run_id: str) -> dict | None:
    terminal = {"paused", "completed", "failed", "cancelled"}
    deadline = time.time() + POLL_TIMEOUT
    while time.time() < deadline:
        data = client.get(f"/runs/{run_id}").json()
        if data["status"] in terminal:
            return data
        time.sleep(POLL_INTERVAL)
    return None


def test_approval_can_link_qa_and_judge_artifacts(client, p6_approval_project):
    project = p6_approval_project
    run_id = client.post("/runs", json=_make_run_payload(project["id"])).json()["id"]
    run = _wait_for_terminal(client, run_id)

    if run is None:
        pytest.skip(f"Run did not complete within {POLL_TIMEOUT}s")
    if run["status"] == "failed":
        pytest.fail(f"Dev cycle run failed: {run.get('error_message')}")

    artifacts = client.get(f"/runs/{run_id}/artifacts").json()
    qa_art = next((a for a in artifacts if a["artifact_type"] == "test_results"), None)
    judge_art = next((a for a in artifacts if a["artifact_type"] == "rubric_score"), None)

    assert qa_art is not None, "test_results artifact missing"
    assert judge_art is not None, "rubric_score artifact missing"

    approval_response = client.post(
        "/approvals",
        json={
            "entity_type": "project",
            "entity_id": project["id"],
            "approved_revision_number": project["current_version"],
            "status": "approved",
            "comment": "QA and judge evidence both support approval for the current project revision.",
            "override_used": False,
            "evidence": [
                {
                    "evidence_type": "test_result",
                    "artifact_id": qa_art["id"],
                    "description": "QA test results generated by the full dev_cycle validation run.",
                },
                {
                    "evidence_type": "artifact",
                    "artifact_id": judge_art["id"],
                    "description": "Judge rubric generated by the full dev_cycle validation run.",
                },
            ],
        },
    )
    assert approval_response.status_code == 201, approval_response.text
    approval = approval_response.json()

    artifact_ids = {item["artifact_id"] for item in approval["evidence"]}
    assert qa_art["id"] in artifact_ids
    assert judge_art["id"] in artifact_ids
    assert {item["evidence_type"] for item in approval["evidence"]} == {"test_result", "artifact"}

    approvals = client.get(f"/entities/project/{project['id']}/approvals").json()
    assert approvals["total"] >= 1
    assert approvals["items"][0]["id"] == approval["id"]
